# This workflow builds the NetEx.Legacy libraries, and uploads the generated NuGet package files as artifacts. The workflow is triggered
# on pull requests and pushes to `main`, can be called from other workflows, or invoked manually.

name: Build Libraries

on:
  pull_request:
    branches:
      - main
    paths:
      - src/**
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_call:
    inputs:
      commit:
        description: 'Commit to build (Optional)'
        required: false
        type: string
  workflow_dispatch:
  
env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: 9.0.x

jobs:

  Build:
    runs-on: windows-latest

    steps:
    
    # Checkout the repository.
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.commit || github.ref }}

    # Set up .NET environment.
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore dependencies.
    - name: Restore Dependencies
      run: dotnet restore
      working-directory: src

    # Build the project.
    - name: Build
      run: |
        dotnet build NetEx.Legacy.WinForms/NetEx.Legacy.WinForms.csproj --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore
      working-directory: src

    # Upload build artifacts.
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nupkg-files
        path: src/**/*.nupkg