name: Release-New

on:
  workflow_dispatch:

env:
  BUILD_CONFIGURATION: Release

jobs:

  # Do a build first to verify the code is valid, and get our new version number.
  Validate:
    uses: ./.github/workflows/build-libraries.yml

  # Now we know everything is valid, we'll update the version number in the source, and tag the latest commit.
  Tag:
    runs-on: windows-latest
    needs: Validate

    steps:

    # Output the version number from the Validate job.
    - name: Show Version Number
      run: "echo Output: ${{ needs.Validate.outputs.version }}"
    
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set the version number in the source project files.
    - name: Set Version Number
      uses: vers-one/dotnet-project-version-updater@v1.7
      with:
        file: |
          "**/*.csproj", "**/*.nuspec", "**/AssemblyInfo.cs"
        version: ${{ needs.Validate.outputs.version }}

    # Commit the changes ready for our production build.
    - name: Commit Version Number
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "chore: update project versions to ${{ needs.Validate.outputs.version }}"
        git push

    # Create a tag for the latest commit.
    - name: Tag Release Version
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ needs.Validate.outputs.version }}
        tag_exists_error: false
        message: Latest release

  # Now do our build for real.
  Build:
    needs: Tag
    uses: ./.github/workflows/build-libraries.yml

  Publish:
    runs-on: windows-latest
    needs: [Validate, Build]

    steps:

    # Download build artifacts
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: nupkg-files

    # Create a GitHub release
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ needs.Validate.outputs.version }}
        release_name: v${{ needs.Validate.outputs.version }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: true
        prerelease: false

    # Upload the build output to the release
    #- name: Upload to Release
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    files: ./**/*.nupkg

    # Publish the build packages to NuGet
    #- name: Publish to NuGet
    #  run: dotnet nuget push "**/NetEx.*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}

  Documentation:
    needs: Publish
    uses: ./.github/workflows/publish-documentation.yml